-- ============================================================
-- OpsTracker — Database Initialization Script
-- Run once against MySQL 8.0 to create the schema and seed data.
--
-- Usage:
--   mysql -u root -p < schema.sql
--
-- Or mount into Docker:
--   /docker-entrypoint-initdb.d/schema.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS opstracker
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE opstracker;

-- -----------------------------------------------------------
-- 1. Users
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    full_name   VARCHAR(120)    NOT NULL,
    email       VARCHAR(255)    NOT NULL UNIQUE,
    password_hash VARCHAR(255)  NOT NULL,
    role        ENUM('Admin', 'Employee') NOT NULL DEFAULT 'Employee',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_users_email (email)
) ENGINE=InnoDB;

-- -----------------------------------------------------------
-- 2. Teams
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS teams (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    team_name   VARCHAR(120) NOT NULL,
    description TEXT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- -----------------------------------------------------------
-- 3. Team_Members (many-to-many mapping)
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS team_members (
    user_id INT NOT NULL,
    team_id INT NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, team_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- -----------------------------------------------------------
-- 4. Projects
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    description TEXT,
    status      ENUM('Ongoing', 'Completed') NOT NULL DEFAULT 'Ongoing',
    team_id     INT NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
    INDEX idx_projects_team (team_id)
) ENGINE=InnoDB;

-- -----------------------------------------------------------
-- 5. Tasks
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS tasks (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(200) NOT NULL,
    status      ENUM('To-Do', 'In-Progress', 'Done') NOT NULL DEFAULT 'To-Do',
    due_date    DATE,
    project_id  INT NOT NULL,
    assigned_to INT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_tasks_project (project_id),
    INDEX idx_tasks_assigned (assigned_to)
) ENGINE=InnoDB;

-- -----------------------------------------------------------
-- Seed: Default Admin User
-- Email:    admin@opstracker.local
-- Password: admin123
-- Hash generated by: werkzeug.security.generate_password_hash("admin123")
-- -----------------------------------------------------------
INSERT INTO users (full_name, email, password_hash, role)
VALUES (
    'System Admin',
    'admin@opstracker.local',
    'scrypt:32768:8:1$2Yp3UgsVEDTNulHi$90964c5ca198a7810a435c9b2be9884ce93401ca65adeca153543236bc186372b3c85d115e63a9d5d2d926612cee9c282be6b2eab2307484d252bfe42c55542e',
    'Admin'
);
